/* CREATE DATABASE */

CREATE USER user1234
IDENTIFIED BY pass1234
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA 10M ON users;

GRANT connect to user1234;
GRANT resource to user1234;
GRANT create session TO user1234;
GRANT create table TO user1234;
GRANT create view TO user1234;



conn user1234/pass1234


/* CREATE TABLE */
CREATE TABLE EMPLOYEE
(
    EMPLOYEEID NUMBER NOT NULL,
    FIRST_NAME VARCHAR2(20) NOT NULL,
    LAST_NAME VARCHAR2(20) NOT NULL,
    USERNAME VARCHAR2(20) NOT NULL,
    PASSWORD VARCHAR2(20) NOT NULL,
    TITLE VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMPLOYEEID)
);

CREATE TABLE REQUEST
(
    REQUEST_ID NUMBER NOT NULL,
    FIRST_NAME VARCHAR2(20) NOT NULL,
    LAST_NAME VARCHAR2(20) NOT NULL,
    AMOUNT NUMBER NOT NULL,
    EVENT_DATE TIMESTAMP NOT NULL,
    LOCATION VARCHAR2(20) NOT NULL,
    DESCRIPTION VARCHAR2(20),
    GRADING_FORMAT VARCHAR2(20) NOT NULL,
    EVENT_TYPE VARCHAR2(20),
    JUSTIFICATION VARCHAR2(20) NOT NULL,
    STATUS NUMBER NOT NULL,
    E_ID NUMBER NOT NULL,
    CONSTRAINT PK_REQUEST PRIMARY KEY (REQUEST_ID),
    CONSTRAINT FK_REQUEST_EMPLOYEE FOREIGN KEY (E_ID) REFERENCES EMPLOYEE (EMPLOYEEID)
);

CREATE TABLE LOG
(
    ID NUMBER NOT NULL,
    ACTION VARCHAR2(20) NOT NULL,
    TIME TIMESTAMP NOT NULL,
    CONSTRAINT PK_LOG PRIMARY KEY (ID)
);

CREATE SEQUENCE REQUEST_ID
  START WITH    1
  INCREMENT BY  1;

CREATE OR REPLACE TRIGGER CREATE_REQUEST_ID
  BEFORE INSERT ON REQUEST
  FOR EACH ROW
  BEGIN
    SELECT REQUEST_ID.NEXTVAL INTO :new.REQUEST_ID FROM DUAL;
  END;
  /

create OR replace procedure set_Employee_RequestID(E_ID IN Number, R_ID IN NUMBER)
AS
BEGIN
    UPDATE EMPLOYEE SET REQUEST_ID = R_ID WHERE EMPLOYEEID = E_ID;
END;
/


/*INSERT INTO EMPLOYEE values (1,'HAIHOUA','YANG','yangh1','pass','employee');*/
  
commit;


