/* CREATE DATABASE */

CREATE USER user1234
IDENTIFIED BY pass1234
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA 10M ON users;

GRANT connect to user1234;
GRANT resource to user1234;
GRANT create session TO user1234;
GRANT create table TO user1234;
GRANT create view TO user1234;



conn user1234/pass1234

/* CREATE TABLE */

CREATE TABLE REQUEST
(
    REQUEST_ID NUMBER NOT NULL,
    FIRST_NAME VARCHAR2(20) NOT NULL,
    LAST_NAME VARCHAR2(20) NOT NULL,
    AMOUNT NUMBER NOT NULL,
    EVENT_DATE DATE NOT NULL,
    EVENT_TIME TIMESTAMP NOT NULL,
    LOCATION VARCHAR2(20) NOT NULL,
    DESCRIPTION VARCHAR2(20),
    /*COST NUMBER,*/
    GRADING_FORMAT VARCHAR2(20) NOT NULL,
    EVENT_TYPE VARCHAR2(20),
    JUSTIFICATION VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_REQUEST PRIMARY KEY (REQUEST_ID)
);

CREATE TABLE EMPLOYEE
(
    ID NUMBER NOT NULL,
    FIRST_NAME VARCHAR2(20) NOT NULL,
    LAST_NAME VARCHAR2(20) NOT NULL,
    REQUEST_ID NUMBER NOT NULL,
    USERNAME VARCHAR2(20) NOT NULL,
    PASSWORD VARCHAR2(20) NOT NULL,
    TITLE VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (ID),
    CONSTRAINT FK_EMPLOYEE FOREIGN KEY (REQUEST_ID) REFERENCES REQUEST (REQUEST_ID)
);

CREATE TABLE LOG
(
    ID NUMBER NOT NULL,
    ACTION VARCHAR2(20) NOT NULL,
    TIME TIMESTAMP NOT NULL,
    CONSTRAINT PK_LOG PRIMARY KEY (ID)
);

CREATE SEQUENCE REQUEST_ID
  START WITH    1
  INCREMENT BY  1;

CREATE OR REPLACE TRIGGER CREATE_REQUEST_ID
  BEFORE INSERT ON REQUEST
  FOR EACH ROW
  BEGIN
    SELECT REQUEST_ID.NEXTVAL INTO :new.REQUEST_ID FROM DUAL;
  END;
  /
  
alter TABLE REQUEST DROP COLUMN EVENT_TIME;
ALTER TABLE REQUEST MODIFY EVENT_DATE TIMESTAMP;
ALTER TABLE REQUEST ADD STATUS NUMBER;
  
commit;



